# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fgh3yD4h8qLvKZfUmBAUYKgEamlM8rRg
"""

# Step 1: Install dependencies (optional, for image display)
!pip install pillow --quiet

# Step 2: Import required libraries
import requests
from PIL import Image
import base64
from io import BytesIO

# Step 3: Define your Stability AI API key
api_key = "sk-b13bqUjr6eQP33B5JhtTLNY6lVrtkuehnDPzNwGr3lI5sPOq"  # 🔐 Replace this with your actual API key

# Step 4: Define the image generation function with correct endpoint
def generate_image(prompt):
    url = "https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }
    payload = {
        "text_prompts": [{"text": prompt}],
        "cfg_scale": 7,
        "height": 1024,
        "width": 1024,
        "samples": 1,
        "steps": 30
    }

    response = requests.post(url, headers=headers, json=payload)

    if response.status_code != 200:
        raise Exception(f"Failed to generate image: {response.status_code}, {response.text}")

    image_data = response.json()["artifacts"][0]["base64"]
    return Image.open(BytesIO(base64.b64decode(image_data)))



# Step 5: Get user prompt, generate and display the image in Colab
from IPython.display import display

prompt = input("Enter your image prompt: ")

try:
    img = generate_image(prompt)
    img.save("generated_image.png")
    display(img)  # ✅ Proper display in Google Colab
except Exception as e:
    print("Error:", e)